const {test}=require('node:test');const assert=require('node:assert/strict');
const {endpoint,validateItems,validateAnalysis,wordCount}=require('../netlify/functions/lib/core.cjs');
const a={bacaanTerdeteksi:[{id:'s1',jenisTeks:'Descriptive',levelCEFR:'A1',teks:'The library is next to the hall. It opens at eight.'}],jumlahSoal:2,bahasa:'Inggris',jenisTeks:'Descriptive',jenisSoal:'Pilihan Ganda',tingkatKesulitan:'Mudah',levelCEFR:'A1',ringkasanPola:'Deskripsi tempat dan informasi rinci.',polaButir:[1,2].map(n=>({nomor:n,jenisSoal:'Pilihan Ganda',jumlahPilihan:3,grupStimulus:'s1',jenisTeks:'Descriptive',tingkatKesulitan:'Mudah — informasi tersurat',taksonomiBarrett:'Literal Comprehension — menemukan informasi tersurat',levelCEFR:'A1',kisiKisi:'Disajikan deskripsi perpustakaan, siswa dapat menentukan lokasi perpustakaan.',pola:'Find details in a short descriptive text.'}))};
const items=[1,2].map(n=>({nomor:n,jenisSoal:'Pilihan Ganda',teksBacaan:'The library is next to the hall. It opens at eight.',pertanyaan:'Where is the library?',pilihan:['A. Next to the hall','B. Behind the park','C. Near the shop'],kunciJawaban:'A'}));
const event=b=>({httpMethod:'POST',headers:{'content-type':'application/json',host:'example.test',origin:'https://example.test'},body:JSON.stringify(b)});
test('reject invalid requests before any provider call',async()=>{for(const [b,code]of[[{textContent:''},'EMPTY'],[{textContent:10},'TEXT'],[{textContent:'hello',images:[{mimeType:'image/svg+xml',data:'xxxx'}]},'IMAGE']]){const r=await endpoint('analyze')(event(b));assert.equal(JSON.parse(r.body).error.code,code);}const r=await endpoint('analyze')({...event({textContent:'x'}),httpMethod:'GET'});assert.equal(r.statusCode,405);});
test('analysis and item validation reject count, option, key, and shared-passage mismatch',()=>{validateAnalysis({valid:true,readable:true,pesan:'',analisis:a});validateItems({items},a,1,2);assert.throws(()=>validateItems({items:items.slice(0,1)},a,1,2));assert.throws(()=>validateItems({items:[items[0],{...items[1],teksBacaan:'Different passage'}]},a,1,2));assert.throws(()=>validateItems({items:[{...items[0],kunciJawaban:'Z'},items[1]]},a,1,2));assert.throws(()=>validateItems({items:[{...items[0],pilihan:['A. Only']},items[1]]},a,1,2));assert.throws(()=>validateItems({items:items.slice(1)},a,2,2,{s1:'Wrong passage'}));});
test('provider fallback on 429 then malformed output then valid Groq; no key leaks',async()=>{const oldFetch=global.fetch,env={...process.env};process.env.GEMINI_API_KEY_1='secret-one';process.env.GEMINI_API_KEY_2='secret-two';process.env.GROQ_API_KEY='secret-three';let calls=[];global.fetch=async(url,opts)=>{calls.push({url,opts});if(calls.length===1)return{ok:false,status:429};if(calls.length===2)return{ok:true,json:async()=>({candidates:[{finishReason:'STOP',content:{parts:[{text:'{}'}]}}]})};return{ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:JSON.stringify({valid:true,readable:true,pesan:'',analisis:a})}}]})};};try{const r=await endpoint('analyze')(event({textContent:'An English test',images:[]}));assert.equal(r.statusCode,200);assert.equal(calls.length,3);assert.ok(calls[0].url.includes('googleapis'));assert.equal(calls[1].opts.headers['x-goog-api-key'],'secret-two');assert.ok(calls[2].url.includes('groq'));assert.ok(!r.body.includes('secret'));}finally{global.fetch=oldFetch;process.env=env;}});
test('missing keys return a clear configuration error',async()=>{const env={...process.env};delete process.env.GEMINI_API_KEY_1;delete process.env.GEMINI_API_KEY_2;delete process.env.GROQ_API_KEY;try{const r=await endpoint('analyze')(event({textContent:'An English test'}));assert.equal(r.statusCode,503);assert.equal(JSON.parse(r.body).error.code,'CONFIG');}finally{process.env=env;}});
test('cross-origin request refused',async()=>{const r=await endpoint('analyze')({...event({textContent:'x'}),headers:{'content-type':'application/json',host:'example.test',origin:'https://other.test'}});assert.equal(r.statusCode,403);});

test('per-item review requires all six requested fields',()=>{for(const k of ['jenisTeks','jenisSoal','tingkatKesulitan','taksonomiBarrett','levelCEFR','kisiKisi']){const b=structuredClone(a);delete b.polaButir[0][k];assert.throws(()=>validateAnalysis({valid:true,readable:true,pesan:'',analisis:b}),k);}});

test('passages counted deterministically and linked to all source items',()=>{const b=structuredClone(a);b.bacaanTerdeteksi[0].jumlahKata=999;b.bacaanTerdeteksi[0].untukSoal=[99];validateAnalysis({valid:true,readable:true,pesan:'',analisis:b});assert.equal(b.bacaanTerdeteksi[0].jumlahKata,11);assert.deepEqual(b.bacaanTerdeteksi[0].untukSoal,[1,2]);assert.equal(wordCount("Don't count well-known punctuation — twice!"),5);const missing=structuredClone(a);missing.bacaanTerdeteksi=[];assert.throws(()=>validateAnalysis({valid:true,readable:true,pesan:'',analisis:missing}));const none=structuredClone(a);none.bacaanTerdeteksi=[];none.polaButir.forEach(p=>p.grupStimulus=null);validateAnalysis({valid:true,readable:true,pesan:'',analisis:none});});
